# -- 코드를 입력하세요
# SELECT AUTHOR.AUTHOR_ID ,AUTHOR_NAME,CATEGORY,(SUM(PRICE*SALES))AS TOTAL_SALES
# FROM BOOK,AUTHOR,BOOK_SALES 
# WHERE BOOK.BOOK_ID=BOOK_SALES.BOOK_ID AND AUTHOR.AUTHOR_ID=BOOK.AUTHOR_ID
#         AND SALES_DATE LIKE ("%2022-01%")
# GROUP BY AUTHOR.AUTHOR_ID,CATEGORY
# ORDER BY AUTHOR.AUTHOR_ID ASC, CATEGORY DESC

SELECT 
       A.AUTHOR_ID ,
       B.AUTHOR_NAME,
       A.CATEGORY ,
       SUM(SALES * A.PRICE) AS TOTAL_SALES
       
  FROM BOOK A, AUTHOR B, BOOK_SALES C
 WHERE A.AUTHOR_ID = B.AUTHOR_ID
   AND A.BOOK_ID = C.BOOK_ID
   AND C.SALES_DATE LIKE ("%2022-01%")
 GROUP BY A.AUTHOR_ID , A.CATEGORY 
 ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC