 SELECT YEAR,
         ROUND(AVG(PM_VAL1),2) AS "PM10",	
         ROUND(AVG(PM_VAL2),2) AS "PM2.5"
 FROM    (SELECT LOCATION1,LOCATION2,YEAR(YM) AS YEAR,PM_VAL1,PM_VAL2
             FROM AIR_POLLUTION) AS A
 WHERE  A.LOCATION2 = "수원"    
 GROUP BY A.YEAR
 ORDER BY A.YEAR ASC;

# SELECT YEAR(YM) AS YEAR,
#        ROUND(AVG(PM_VAL1), 2) AS "PM10",
#        ROUND(AVG(PM_VAL2), 2) AS "PM2.5"
# FROM   AIR_POLLUTION 
# WHERE  LOCATION2 LIKE "%수원%"
# GROUP BY YEAR(YM)
# ORDER BY YEAR;