-- 코드를 입력하세요

WITH A AS(
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                         WHERE END_DATE >= '2022-11-1' 
                               AND START_DATE <= '2022-11-30')

) 
SELECT A.CAR_ID ,B.CAR_TYPE,
   ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) )AS FEE
FROM A , CAR_RENTAL_COMPANY_CAR  B ,CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    WHERE A.CAR_ID= B.CAR_ID
        AND B.CAR_TYPE=C.CAR_TYPE
        AND C.DURATION_TYPE LIKE "30%"
GROUP BY A.CAR_ID
HAVING FEE<2000000 AND FEE>=500000
ORDER BY FEE DESC, B.CAR_TYPE ASC, A.CAR_ID DESC
 # SELECT car_id,START_DATE	,END_DATE
 # from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 # where car_id =18

# SELECT CAR_ID, C.CAR_TYPE, 
#        FLOOR(30*DAILY_FEE*(1-DISCOUNT_RATE/100)) AS FEE 
# FROM CAR_RENTAL_COMPANY_CAR C 
#      JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE) 
# WHERE C.CAR_TYPE IN ('세단', 'SUV') 
#       AND CAR_ID NOT IN (SELECT CAR_ID
#                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#                          WHERE END_DATE >= '2022-11-1' 
#                                AND START_DATE <= '2022-11-30')
#       AND DURATION_TYPE = '30일 이상'
# HAVING FEE >= 500000 AND FEE < 2000000 
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC 