-- 코드를 작성해주세요
WITH COLONYGROUPS AS (
SELECT
ID,
NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GROUPRANK
FROM ECOLI_DATA
)

SELECT
    ID,
    CASE
    WHEN GROUPRANK = 1 THEN 'CRITICAL'
    WHEN GROUPRANK = 2 THEN 'HIGH'
    WHEN GROUPRANK = 3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
    FROM COLONYGROUPS
ORDER BY ID;