-- 코드를 입력하세요
SELECT USER_ID,NICKNAME	,CONCAT(CITY, " " , STREET_ADDRESS1," ",STREET_ADDRESS2)	,  CONCAT(
        SUBSTRING(TLNO, 1, 3), '-',
        SUBSTRING(TLNO, 4, 4), '-',
        SUBSTRING(TLNO, 8)
    ) AS 전화번호
FROM USED_GOODS_BOARD, USED_GOODS_USER 
WHERE USED_GOODS_BOARD.WRITER_ID= USED_GOODS_USER.USER_ID
GROUP BY USER_ID
HAVING COUNT(BOARD_ID)>2
ORDER BY USER_ID DESC