-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.ANIMAL_TYPE,ANIMAL_INS.NAME
FROM ANIMAL_INS ,ANIMAL_OUTS 
WHERE ANIMAL_OUTS.ANIMAL_ID= ANIMAL_INS.ANIMAL_ID
    AND ANIMAL_INS.SEX_UPON_INTAKE LIKE "Intact %"
    AND (ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Spayed%"
         OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Neutered%")
ORDER BY ANIMAL_INS.ANIMAL_ID ASC