SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y") AS YEAR,
    #SUBSTR(DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%m"), 2, 2) AS MONTH,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
   USER_INFO.GENDER,
   COUNT(DISTINCT(ONLINE_SALE.USER_ID)) AS USERS
FROM ONLINE_SALE, USER_INFO
WHERE ONLINE_SALE.USER_ID = USER_INFO.USER_ID AND USER_INFO.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, USER_INFO.GENDER
ORDER BY YEAR ASC, MONTH ASC, USER_INFO.GENDER ASC;


# SELECT YEAR(SALES_DATE) AS YEAR,
#        MONTH(SALES_DATE) AS MONTH,
#        GENDER,
#        COUNT(DISTINCT USER_ID) AS USERS
# FROM ONLINE_SALE JOIN USER_INFO USING (USER_ID)
# WHERE GENDER IS NOT NULL 
# GROUP BY  YEAR, MONTH, GENDER
# ORDER BY  YEAR, MONTH, GENDER