-- 코드를 입력하세요
SELECT HISTORY_ID,CAR_ID,
        DATE_FORMAT(START_DATE,"%Y-%m-%d") AS START_DATE,
        DATE_FORMAT(END_DATE,"%Y-%m-%d") AS END_DATE, 
        #IF (END_DATE-START_DATE+1>30 , '장기 대여', '단기 대여') AS RENT_TYPE
        IF(DATEDIFF(END_DATE, START_DATE)+1 >= 30, "장기 대여","단기 대여") AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE> "2022-08-31" AND START_DATE<"2022-10-01" ) 
#        AND CASE WHEN (END_DATE-START_DATE)>=30 THEN
        
# CASE WHEN PRD_NUM = 'P001' THEN '제품1'
#             WHEN PRD_NUM = 'P002' THEN '제품2'
#    		  ELSE NULL
#       END AS PRD_NUM1
ORDER BY HISTORY_ID DESC

# SELECT HISTORY_ID,
#         CAR_ID,
#         DATE_FORMAT(start_date,'%Y-%m-%d') AS START_DATE,
#         DATE_FORMAT(end_date,'%Y-%m-%d') AS END_DATE,
#         IF(DATEDIFF(END_DATE, START_DATE)+1 >= 30, "장기 대여","단기 대여") AS RENT_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE,'%Y-%m') = '2022-09'
# ORDER BY history_id DESC