-- 코드를 입력하세요

# SELECT FOOD_PRODUCT.PRODUCT_ID ,PRODUCT_NAME, (A.AM*PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT,
# (SELECT PRODUCT_ID, SUM(AMOUNT) AS AM
# FROM FOOD_ORDER 
# WHERE produce_date LIKE "2022-05%"
# GROUP BY PRODUCT_ID)AS A
# WHERE A.PRODUCT_ID= FOOD_PRODUCT.PRODUCT_ID
# GROUP BY PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC ,FOOD_PRODUCT.PRODUCT_ID ASC



SELECT P.PRODUCT_ID,
       PRODUCT_NAME,
        SUM(AMOUNT*P.PRICE) AS TOTAL_SALES
        
FROM FOOD_PRODUCT AS P , FOOD_ORDER AS O
WHERE P.PRODUCT_ID=O.PRODUCT_ID
     AND produce_date LIKE "2022-05%"
GROUP BY P.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;









