# -- 코드를 입력하세요
# WITH A AS(
# SELECT CAR_TYPE, DAILY_FEE, HISTORY_ID,  CASE  
#         WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN "90일 이상"
#         WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN "30일 이상"
#         WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN "7일 이상"
#         ELSE NULL
#        END AS D1
#     ,DATEDIFF(END_DATE,START_DATE)+1 AS D2
# FROM CAR_RENTAL_COMPANY_CAR , CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID= CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
#         AND CAR_TYPE LIKE "트럭"
#     ),
# B AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE CAR_TYPE LIKE "트럭"
# )
# SELECT HISTORY_ID,
#        CASE
#        WHEN B.DISCOUNT_RATE IS NOT NULL THEN ROUND(D2*DAILY_FEE * (1-(DISCOUNT_RATE/100)),0)
#        ELSE D2*DAILY_FEE 
#        END AS FEE

# FROM A LEFT JOIN B ON
#     A.D1= B.DURATION_TYPE
# ORDER BY FEE DESC, HISTORY_ID DESC





 WITH A AS(
            SELECT R.CAR_ID, R.CAR_TYPE, H.HISTORY_ID, R.DAILY_FEE,
              CASE
                  WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN '90일 이상'
                  WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN '30일 이상'
                  WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN '7일 이상'
                  ELSE NULL
               END AS D1
             ,DATEDIFF(END_DATE,START_DATE)+1 AS D2
        FROM CAR_RENTAL_COMPANY_CAR R,
             CAR_RENTAL_COMPANY_RENTAL_HISTORY  H
        WHERE R.CAR_ID = H.CAR_ID
          AND CAR_TYPE LIKE "트럭" 
 ),
B AS (
    SELECT *
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
     WHERE CAR_TYPE LIKE "트럭"
)

SELECT HISTORY_ID, 
      CASE 
            WHEN D1 IS NOT NULL THEN (100-DISCOUNT_RATE)/100 * DAILY_FEE *D2
            #WHEN B.DISCOUNT_RATE IS NOT NULL THEN ROUND(D2*DAILY_FEE * (1-(DISCOUNT_RATE/100)),0)
            ELSE A.DAILY_FEE *D2
       END AS FEE
       # A.*,B.*

  FROM A LEFT JOIN B 
    ON A.D1= B.DURATION_TYPE
    ORDER BY FEE DESC, HISTORY_ID DESC
 










