-- 코드를 입력하세요
WITH A AS(
SELECT CAR_TYPE, DAILY_FEE, HISTORY_ID,  CASE  
        WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN "7일 이상"
        ELSE NULL
       END AS D1
    ,DATEDIFF(END_DATE,START_DATE)+1 AS D2
FROM CAR_RENTAL_COMPANY_CAR , CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID= CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
        AND CAR_TYPE LIKE "트럭"
    ),
B AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE LIKE "트럭"
)
SELECT HISTORY_ID,
       CASE
       WHEN B.DISCOUNT_RATE IS NOT NULL THEN ROUND(D2*DAILY_FEE * (1-(DISCOUNT_RATE/100)),0)
       ELSE D2*DAILY_FEE 
       END AS FEE

FROM A LEFT JOIN B ON
    A.D1= B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
