-- 코드를 입력하세요
# SELECT MEMBER_NAME,
#         REVIEW_TEXT,
#         DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE
# FROM REST_REVIEW,MEMBER_PROFILE 
# WHERE REST_REVIEW.MEMBER_ID= MEMBER_PROFILE.MEMBER_ID
#     and REST_REVIEW.MEMBER_ID =
#         (       
#             SELECT MEMBER_ID FROM REST_REVIEW
#             GROUP BY MEMBER_ID
#             ORDER BY COUNT(*) DESC LIMIT 1
#          )
# ORDER BY REVIEW_DATE ASC,REVIEW_TEXT ASC;
 # select MEMBER_ID, COUNT(MEMBER_ID)
 #        FROM REST_REVIEW 
 #        GROUP BY MEMBER_ID 
 #        ORDER BY COUNT(*) DESC LIMIT 1;


SELECT A.MEMBER_NAME,
       B.REVIEW_TEXT,
      B.REVIEW_DATE
FROM MEMBER_PROFILE A,REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
  AND A.MEMBER_ID = (
                      SELECT  MEMBER_ID
                        FROM REST_REVIEW 
                        GROUP BY MEMBER_ID
                        ORDER BY COUNT(*)  DESC LIMIT 1
                   )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT asc;




