-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR
FROM FIRST_HALF , ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR=ICECREAM_INFO.FLAVOR AND TOTAL_ORDER>3000 AND INGREDIENT_TYPE  LIKE "fruit_based"
ORDER BY TOTAL_ORDER DESC