-- 코드를 작성해주세요

# SELECT 
#     YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
#     max_sizes.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
#     e.ID
# FROM 
#     ECOLI_DATA e
# JOIN 
#     (SELECT 
#         YEAR(DIFFERENTIATION_DATE) AS YEAR,
#         MAX(SIZE_OF_COLONY) AS MAX_SIZE
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)) max_sizes
# ON YEAR(e.DIFFERENTIATION_DATE) = max_sizes.YEAR
# ORDER BY YEAR, YEAR_DEV;
SELECT 
    YEAR(e.DIFFERENTIATION_DATE) YEAR,
    (m.MAX_SIZE-e.size_of_colony) YEAR_DEV,
    e.ID 
FROM ECOLI_DATA e
JOIN 
    (SELECT 
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) m
ON YEAR(e.DIFFERENTIATION_DATE)= m.YEAR
ORDER BY YEAR, YEAR_DEV;
