-- 코드를 입력하세요
SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR ,CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID=CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
AND START_DATE LIKE "_____10%" AND CAR_TYPE LIKE "세단"
GROUP BY CAR_RENTAL_COMPANY_CAR.CAR_ID
ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC