-- 코드를 작성해주세요
# with T AS(SELECT A.FISH_TYPE AS FISH_TYPE,MAX(LENGTH) AS LENGTH1,FISH_NAME
# FROM FISH_INFO AS A
# JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
# GROUP BY A.FISH_TYPE,FISH_NAME)

# SELECT *
# FROM FISH_INFO,T
# WHERE FISH_INFO.FISH_TYPE=T.FISH_TYPE
# GROUP BY T.FISH_TYPE
SELECT A.ID,
       B.FISH_NAME,
       A.LENGTH
FROM FISH_INFO A,FISH_NAME_INFO B

WHERE A.FISH_TYPE = B.FISH_TYPE
  AND A.LENGTH = (
                        SELECT MAX(C.LENGTH)
                        FROM FISH_INFO C
                        WHERE C.FISH_TYPE = A.FISH_TYPE
                    )
ORDER BY A.ID


# WITH T AS(

# SELECT MAX(LENGTH) LENGTH,  A.FISH_TYPE, FISH_NAME
# FROM FISH_INFO A, FISH_NAME_INFO B
# WHERE A.FISH_TYPE = B.FISH_TYPE
# GROUP BY FISH_TYPE , FISH_NAME

# )
# SELECT 	A.FISH_NAME, T.LENGTH
# FROM FISH_NAME_INFO A, T
# WHERE T.FISH_TYPE = A.FISH_TYPE



