# -- 코드를 작성해주세요
# with T AS(SELECT A.FISH_TYPE AS FISH_TYPE,MAX(LENGTH) AS LENGTH1,FISH_NAME
# FROM FISH_INFO AS A
# JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
# GROUP BY A.FISH_TYPE,FISH_NAME)

# SELECT *
# FROM FISH_INFO,T
# WHERE FISH_INFO.FISH_TYPE=T.FISH_TYPE
# GROUP BY T.FISH_TYPE
# # SELECT A.FISH_TYPE AS FISH_TYPE,MAX(LENGTH) AS LENGTH1,FISH_NAME
# # FROM FISH_INFO AS A
# # JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
# # GROUP BY A.FISH_TYPE,FISH_NAME
WITH T AS (
    SELECT 
        A.FISH_TYPE, 
        MAX(A.LENGTH) AS MAX_LENGTH
    FROM 
        FISH_INFO AS A
    GROUP BY 
        A.FISH_TYPE
)

SELECT 
    F.ID, 
    B.FISH_NAME,
    F.LENGTH
FROM 
    FISH_INFO AS F
JOIN 
    T ON F.FISH_TYPE = T.FISH_TYPE AND F.LENGTH = T.MAX_LENGTH
JOIN 
    FISH_NAME_INFO AS B ON F.FISH_TYPE = B.FISH_TYPE;
