-- 코드를 작성해주세요
SELECT  HR_DEPARTMENT.DEPT_ID,
        HR_DEPARTMENT.DEPT_NAME_EN,
        ROUND(SUM(SAL)/COUNT(EMP_NO))AS AVG_SAL
FROM HR_DEPARTMENT,HR_EMPLOYEES
WHERE HR_DEPARTMENT.DEPT_ID=HR_EMPLOYEES.DEPT_ID
GROUP BY HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC